import './globals.css'
import Header from '../../componentes/cabecalho/header'
import Footer from '../../componentes/cabecalho/footer'
import { playfair_display } from '@/fonts';

export const metadata = {
  title: 'Grão de Café',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" >
      <body className={playfair_display.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
